/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "pubsub_config_static.h"

#include <stdbool.h>
#include <string.h>

#include "sopc_assert.h"
#include "sopc_pubsub_conf.h"
#include "sopc_crypto_profiles_lib_itf.h"
#include "samples_platform_dep.h"
#include "test_config.h"

// DO NOT EDIT THIS FILE HAS BEEN GENERATED BY generate-s2opc_pubsub-static-config.py


static SOPC_DataSetWriter* SOPC_PubSubConfig_SetPubMessageAt(SOPC_PubSubConnection* connection,
                                                             uint16_t index,
                                                             uint16_t messageId,
                                                             uint32_t version,
                                                             uint64_t interval,
                                                             SOPC_SecurityMode_Type securityMode)

{
    SOPC_WriterGroup* group = SOPC_PubSubConnection_Get_WriterGroup_At(connection, index);
    SOPC_WriterGroup_Set_Id(group, messageId);
    SOPC_WriterGroup_Set_Version(group, version);
    SOPC_WriterGroup_Set_PublishingInterval(group, (double) interval);
    SOPC_WriterGroup_Set_SecurityMode(group, securityMode);

    // Create one DataSet Writer
    SOPC_WriterGroup_Allocate_DataSetWriter_Array(group, 1);
    SOPC_DataSetWriter* writer = SOPC_WriterGroup_Get_DataSetWriter_At(group, 0);
    SOPC_DataSetWriter_Set_Id(writer, messageId);
    return writer;
}

static SOPC_PublishedDataSet* SOPC_PubSubConfig_InitDataSet(SOPC_PubSubConfiguration* config,
                                                            uint16_t dataSetIndex,
                                                            SOPC_DataSetWriter* writer,
                                                            uint16_t nbVar)
{
    SOPC_PublishedDataSet* dataset = SOPC_PubSubConfiguration_Get_PublishedDataSet_At(config, dataSetIndex);
    SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataItemsDataType, nbVar);
    SOPC_DataSetWriter_Set_DataSet(writer, dataset);

    return dataset;
}

static void SOPC_PubSubConfig_SetPubVariableAt(SOPC_PublishedDataSet* dataset,
                                               uint16_t index,
                                               char* strNodeId,
                                               SOPC_BuiltinId builtinType)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_PublishedDataSet_Get_FieldMetaData_At(dataset, index);
    SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = -1, .arrayDimensions = NULL};
    SOPC_FieldMetaData_ArrayDimension_Move(fieldmetadata, &arrayDimension);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
    SOPC_PublishedVariable* publishedVar = SOPC_FieldMetaData_Get_PublishedVariable(fieldmetadata);
    SOPC_ASSERT(NULL != publishedVar);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_ASSERT(NULL != nodeId);
    SOPC_PublishedVariable_Set_NodeId(publishedVar, nodeId);
    SOPC_PublishedVariable_Set_AttributeId(publishedVar,
                                           13); // Value => AttributeId=13
}

static void SOPC_PubSubConfig_SetPubVariableAt_arr(SOPC_PublishedDataSet* dataset,
                                               uint16_t index,
                                               const char* strNodeId,
                                               SOPC_BuiltinId builtinType,
                                               int32_t valueRank,
                                               uint32_t* arrayDimensions)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_PublishedDataSet_Get_FieldMetaData_At(dataset, index);
    SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = valueRank, .arrayDimensions = arrayDimensions};
    SOPC_FiledMetaDeta_SetCopy_ArrayDimension(fieldmetadata, &arrayDimension);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
    SOPC_PublishedVariable* publishedVar = SOPC_FieldMetaData_Get_PublishedVariable(fieldmetadata);
    SOPC_ASSERT(NULL != publishedVar);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_ASSERT(NULL != nodeId);
    SOPC_PublishedVariable_Set_NodeId(publishedVar, nodeId);
    SOPC_PublishedVariable_Set_AttributeId(publishedVar,
                                           13); // Value => AttributeId=13
}




SOPC_PubSubConfiguration* SOPC_PubSubConfig_GetStatic(void)
{
    bool alloc = true;
    SOPC_PubSubConfiguration* config = SOPC_PubSubConfiguration_Create();
    
    SOPC_PubSubConnection* connection = NULL;

    /* 1 publisher connection */
    alloc = SOPC_PubSubConfiguration_Allocate_PubConnection_Array(config, 1);
    
    /* 2 Published Datasets */
    alloc = SOPC_PubSubConfiguration_Allocate_PublishedDataSet_Array(config, 2);
    
    /** Publisher connection 0 **/
    
    if (alloc)
    {
        // Set address
        connection = SOPC_PubSubConfiguration_Get_PubConnection_At(config, 0);
        SOPC_ASSERT(NULL != connection);
        alloc = SOPC_PubSubConnection_Set_Address(connection, "opc.udp://232.1.2.100:4840");
    }
    
        if (alloc)
        {
            // Set publisher id
            SOPC_PubSubConnection_Set_PublisherId_UInteger(connection, 123);
        }
        
    // Set acyclic publisher mode
    SOPC_PubSubConnection_Set_AcyclicPublisher(connection, 0);
    
    if (alloc)
    {
        // Allocate 2 writer groups (messages)
        alloc = SOPC_PubSubConnection_Allocate_WriterGroup_Array(connection, 2);
    }

    if (alloc)
    {
        #define PUB_CNX_NAME "PubCnx#1"
        // Set connection name
        alloc = SOPC_PubSubConnection_Set_Name(connection, PUB_CNX_NAME);
    }

    if (alloc)
    {
        const char* itf_name = "";
        if (itf_name[0] == '\0')
        {
            // Force default interface if not specified
            itf_name = SOPC_Platform_Get_Default_Net_Itf();
        }
        if (itf_name[0] != '\0')
        {
            alloc = SOPC_PubSubConnection_Set_InterfaceName(connection, itf_name);
        }
    }



    
    SOPC_DataSetWriter* writer = NULL;
    /*** Pub Message 11 ***/
    
    if (alloc)
    {
        // GroupId = 11
        // GroupVersion = 1
        // Interval = 100.000000 ms
        // Offest = -1 us
        // mqttTopic = NULL
        // encoding = SOPC_MessageEncodeUADP
        writer = SOPC_PubSubConfig_SetPubMessageAt(connection, 0, 11, 1, 100.000000, SOPC_SecurityMode_None);
        alloc = NULL != writer;
    }
    
    /*** DataSetMessage No 1 of message 11 ***/
    
    SOPC_PublishedDataSet* dataset = NULL;
    if (alloc)
    {
        // WriterId = 1
        dataset = SOPC_PubSubConfig_InitDataSet(config, 0, writer, 3);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=2;s=RawSingleSample_X", SOPC_Int32_Id); // X
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 1, "ns=2;s=RawSingleSample_Y", SOPC_Int32_Id); // Y
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 2, "ns=2;s=RawSingleSample_Z", SOPC_Int32_Id); // Z
    }
    
    /*** Pub Message 12 ***/
    
    if (alloc)
    {
        // GroupId = 12
        // GroupVersion = 1
        // Interval = 1000.000000 ms
        // Offest = -1 us
        // mqttTopic = NULL
        // encoding = SOPC_MessageEncodeUADP
        writer = SOPC_PubSubConfig_SetPubMessageAt(connection, 1, 12, 1, 1000.000000, SOPC_SecurityMode_None);
        alloc = NULL != writer;
    }
    
    
    /*** DataSetMessage No 1 of message 12 ***/
    
    if (alloc)
    {
        // WriterId = 1
        dataset = SOPC_PubSubConfig_InitDataSet(config, 1, writer, 4);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        uint32_t arrayDimensions_0[1] = {10};
        SOPC_PubSubConfig_SetPubVariableAt_arr(dataset, 0, "ns=2;s=RawBatch10_X_Array", SOPC_Int32_Id, 1, arrayDimensions_0); // X-Array
        uint32_t arrayDimensions_1[1] = {10};
        SOPC_PubSubConfig_SetPubVariableAt_arr(dataset, 1, "ns=2;s=RawBatch10_Y_Array", SOPC_Int32_Id, 1, arrayDimensions_1); // Y-Array
        uint32_t arrayDimensions_2[1] = {10};
        SOPC_PubSubConfig_SetPubVariableAt_arr(dataset, 2, "ns=2;s=RawBatch10_Z_Array", SOPC_Int32_Id, 1, arrayDimensions_2); // Z-Array
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 3, "ns=2;s=RawBatch10_Time", SOPC_DateTime_Id); // TimeFirstSample
    }
    

    if (!alloc)
    {
        SOPC_PubSubConfiguration_Delete(config);
        return NULL;
    }

    return config;
}
    
