/*
 * Licensed to Systerel under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Systerel licenses this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "pubsub_config_static.h"

#include <stdbool.h>
#include <string.h>

#include "sopc_assert.h"
#include "sopc_crypto_profiles_lib_itf.h"

#include "samples_platform_dep.h"
#include "test_config.h"

// DO NOT EDIT THIS FILE HAS BEEN GENERATED BY generate-s2opc_pubsub-static-config.py



static SOPC_DataSetWriter* SOPC_PubSubConfig_SetPubMessageAt(SOPC_PubSubConnection* connection,
                                                           uint16_t index,
                                                           uint16_t messageId,
                                                           uint32_t version,
                                                           uint64_t interval,
                                                           SOPC_SecurityMode_Type securityMode)
{
    SOPC_WriterGroup* group = SOPC_PubSubConnection_Get_WriterGroup_At(connection, index);
    SOPC_WriterGroup_Set_Id(group, messageId);
    SOPC_WriterGroup_Set_Version(group, version);
    SOPC_WriterGroup_Set_PublishingInterval(group, (double) interval);
    SOPC_WriterGroup_Set_SecurityMode(group, securityMode);

    // 1 dataset writer
    SOPC_WriterGroup_Allocate_DataSetWriter_Array(group, 1);
    SOPC_DataSetWriter* writer = SOPC_WriterGroup_Get_DataSetWriter_At(group,0);
    SOPC_DataSetWriter_Set_Id(writer, messageId);
    return writer;
    // const SOPC_WriterGroup_Options writerGroupOptions = {.useFixedSizeBuffer = isFixedBufferSize};
    // SOPC_WriterGroup_Set_Options(group, &writerGroupOptions);
    // if (offsetUs >=0)
    // {
    //     SOPC_WriterGroup_Set_PublishingOffset(group, offsetUs / 1000);
    // }

    // return group;
}

static SOPC_PublishedDataSet* SOPC_PubSubConfig_InitDataSet(SOPC_PubSubConfiguration* config,
                                                            uint16_t dataSetIndex,
                                                            SOPC_DataSetWriter* writer,
                                                            uint16_t nbVar)
{
    SOPC_PublishedDataSet* dataset = SOPC_PubSubConfiguration_Get_PublishedDataSet_At(config, dataSetIndex);
    SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataItemsDataType, nbVar);
    SOPC_DataSetWriter_Set_DataSet(writer, dataset);

    return dataset;
}
// static SOPC_PublishedDataSet* SOPC_PubSubConfig_InitDataSet(SOPC_PubSubConfiguration* config,
//                                                             uint16_t dataSetIndex,
//                                                             SOPC_DataSetWriter* writer,
//                                                             bool isAcyclic,
//                                                             uint16_t dataSetId,
//                                                             bool useSeqNum,
//                                                             uint16_t nbVar)
// {
//     SOPC_PublishedDataSet* dataset = SOPC_PubSubConfiguration_Get_PublishedDataSet_At(config, dataSetIndex);
//     if(isAcyclic)
//     {
//         SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataSetCustomSourceDataType, nbVar);
//     }
//     else
//     {
//         SOPC_PublishedDataSet_Init(dataset, SOPC_PublishedDataItemsDataType, nbVar);
//     }
//     SOPC_DataSetWriter_Set_DataSet(writer, dataset);
//     SOPC_DataSetWriter_Set_Id(writer, dataSetId);
//     const SOPC_DataSetWriter_Options dsmOptions = {.noUseSeqNum = !useSeqNum};
//     SOPC_DataSetWriter_Set_Options(writer, &dsmOptions);
//
//     return dataset;
// }


static void SOPC_PubSubConfig_SetPubVariableAt_arr(SOPC_PublishedDataSet* dataset,
                                               uint16_t index,
                                               const char* strNodeId,
                                               SOPC_BuiltinId builtinType,
                                               int32_t valueRank,
                                               uint32_t* arrayDimensions)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_PublishedDataSet_Get_FieldMetaData_At(dataset, index);
    SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = valueRank, .arrayDimensions = arrayDimensions};
    SOPC_FiledMetaDeta_SetCopy_ArrayDimension(fieldmetadata, &arrayDimension);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
    SOPC_PublishedVariable* publishedVar = SOPC_FieldMetaData_Get_PublishedVariable(fieldmetadata);
    SOPC_ASSERT(NULL != publishedVar);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_ASSERT(NULL != nodeId);
    SOPC_PublishedVariable_Set_NodeId(publishedVar, nodeId);
    SOPC_PublishedVariable_Set_AttributeId(publishedVar,
                                           13); // Value => AttributeId=13
}


static void SOPC_PubSubConfig_SetPubVariableAt(SOPC_PublishedDataSet* dataset,
                                               uint16_t index,
                                               char* strNodeId,
                                               SOPC_BuiltinId builtinType)
{
    SOPC_FieldMetaData* fieldmetadata = SOPC_PublishedDataSet_Get_FieldMetaData_At(dataset, index);
    SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = -1, .arrayDimensions = NULL};
    SOPC_FieldMetaData_ArrayDimension_Move(fieldmetadata, &arrayDimension);
    SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
    SOPC_PublishedVariable* publishedVar = SOPC_FieldMetaData_Get_PublishedVariable(fieldmetadata);
    SOPC_ASSERT(NULL != publishedVar);
    SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
    SOPC_ASSERT(NULL != nodeId);
    SOPC_PublishedVariable_Set_NodeId(publishedVar, nodeId);
    SOPC_PublishedVariable_Set_AttributeId(publishedVar,
                                           13); // Value => AttributeId=13
}


// static SOPC_ReaderGroup* SOPC_PubSubConfig_SetSubMessageAt(SOPC_PubSubConnection* connection,
//                                                            uint16_t index,
//                                                            SOPC_SecurityMode_Type securityMode,
//                                                            uint16_t groupId,
//                                                            uint32_t groupVersion,
//                                                            SOPC_Conf_PublisherId publisherId,
//                                                            uint16_t nbDataSets,
//                                                            const char* mqttTopic)
// {
//     SOPC_ReaderGroup* readerGroup = SOPC_PubSubConnection_Get_ReaderGroup_At(connection, index);
//     SOPC_ASSERT(readerGroup != NULL);
//     SOPC_ReaderGroup_Set_SecurityMode(readerGroup, securityMode);
//     SOPC_ReaderGroup_Set_GroupVersion(readerGroup, groupVersion);
//     SOPC_ReaderGroup_Set_GroupId(readerGroup, groupId);
//     SOPC_ASSERT(nbDataSets < 0x100);
//     bool allocSuccess = SOPC_ReaderGroup_Allocate_DataSetReader_Array(readerGroup, (uint8_t) nbDataSets);
//     SOPC_ASSERT(allocSuccess);
//     SOPC_ReaderGroup_Set_MqttTopic(readerGroup, mqttTopic);
//     if (SOPC_UInteger_PublisherId == publisherId.type)
//     {
//         SOPC_ReaderGroup_Set_PublisherId_UInteger(readerGroup, publisherId.data.uint);
//     }
//     else
//     {
//         SOPC_ReaderGroup_Set_PublisherId_String(readerGroup, &publisherId.data.string);
//     }
//     return readerGroup;
// }


// static SOPC_DataSetReader* SOPC_PubSubConfig_SetReaderAt(SOPC_ReaderGroup* readerGroup,
//                                                          uint16_t index,
//                                                          uint16_t writerId,
//                                                          double interval)
// {
//     SOPC_ASSERT(index < 0x100);
//     SOPC_DataSetReader* reader = SOPC_ReaderGroup_Get_DataSetReader_At(readerGroup, (uint8_t) index);
//     SOPC_ASSERT(reader != NULL);
//     SOPC_DataSetReader_Set_DataSetWriterId(reader, writerId);
//     SOPC_DataSetReader_Set_ReceiveTimeout(reader, 2.0 * interval);
//     return reader;
// }

// static SOPC_DataSetReader* SOPC_PubSubConfig_SetSubMessageAt(SOPC_PubSubConnection* connection,
//                                                              uint16_t index,
//                                                              uint32_t publisherId,
//                                                              uint16_t messageId,
//                                                              uint32_t version,
//                                                              uint64_t interval,
//                                                              SOPC_SecurityMode_Type securityMode)
// {
//     SOPC_ReaderGroup* readerGroup = SOPC_PubSubConnection_Get_ReaderGroup_At(connection, index);
//     SOPC_ASSERT(readerGroup != NULL);
//     SOPC_ReaderGroup_Set_SecurityMode(readerGroup, securityMode);
//     SOPC_ReaderGroup_Set_GroupVersion(readerGroup, version);
//     SOPC_ReaderGroup_Set_GroupId(readerGroup, messageId);
//     bool allocSuccess = SOPC_ReaderGroup_Allocate_DataSetReader_Array(readerGroup, 1);
//     SOPC_ReaderGroup_Set_PublisherId_UInteger(readerGroup, publisherId);
//     if (allocSuccess)
//     {
//         SOPC_DataSetReader* reader = SOPC_ReaderGroup_Get_DataSetReader_At(readerGroup, 0);
//         SOPC_ASSERT(reader != NULL);
//         SOPC_DataSetReader_Set_DataSetWriterId(reader, messageId);
//         SOPC_DataSetReader_Set_ReceiveTimeout(reader, 2.0 * (double) interval);
//         return reader;
//     }
//     return NULL;
// }
//
//
// static bool SOPC_PubSubConfig_SetSubNbVariables(SOPC_DataSetReader* reader, uint16_t nbVar)
// {
//     return SOPC_DataSetReader_Allocate_FieldMetaData_Array(reader, SOPC_TargetVariablesDataType, nbVar);
// }


// static void SOPC_PubSubConfig_SetSubVariableAt(SOPC_DataSetReader* reader,
//                                                uint16_t index,
//                                                const char* strNodeId,
//                                                SOPC_BuiltinId builtinType,
//                                                int32_t valueRank,
//                                                uint32_t* arrayDimensions)
// {
//     SOPC_FieldMetaData* fieldmetadata = SOPC_DataSetReader_Get_FieldMetaData_At(reader, index);
//     SOPC_ASSERT(fieldmetadata != NULL);
//
//     /* fieldmetadata: type the field */
//     SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
//     SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = valueRank, .arrayDimensions = arrayDimensions};
//     SOPC_FiledMetaDeta_SetCopy_ArrayDimension(fieldmetadata, &arrayDimension);
//     /* FieldTarget: link to the source/target data */
//     SOPC_FieldTarget* fieldTarget = SOPC_FieldMetaData_Get_TargetVariable(fieldmetadata);
//     SOPC_ASSERT(fieldTarget != NULL);
//     SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
//     SOPC_FieldTarget_Set_NodeId(fieldTarget, nodeId);
//     SOPC_FieldTarget_Set_AttributeId(fieldTarget, 13); // Value => AttributeId=13
// }

// static void SOPC_PubSubConfig_SetSubVariableAt(SOPC_DataSetReader* reader,
//                                                uint16_t index,
//                                                char* strNodeId,
//                                                SOPC_BuiltinId builtinType)
// {
//     SOPC_FieldMetaData* fieldmetadata = SOPC_DataSetReader_Get_FieldMetaData_At(reader, index);
//     SOPC_ASSERT(fieldmetadata != NULL);
//
//     /* fieldmetadata: type the field */
//     SOPC_PubSub_ArrayDimension arrayDimension = {.valueRank = -1, .arrayDimensions = NULL};
//     SOPC_FieldMetaData_ArrayDimension_Move(fieldmetadata, &arrayDimension);
//     SOPC_FieldMetaData_Set_BuiltinType(fieldmetadata, builtinType);
//
//     /* FieldTarget: link to the source/target data */
//     SOPC_FieldTarget* fieldTarget = SOPC_FieldMetaData_Get_TargetVariable(fieldmetadata);
//     SOPC_ASSERT(fieldTarget != NULL);
//     SOPC_NodeId* nodeId = SOPC_NodeId_FromCString(strNodeId, (int32_t) strlen(strNodeId));
//     SOPC_FieldTarget_Set_NodeId(fieldTarget, nodeId);
//     SOPC_FieldTarget_Set_AttributeId(fieldTarget, 13); // Value => AttributeId=13
// }


SOPC_PubSubConfiguration* SOPC_PubSubConfig_GetStatic(void)
{
    bool alloc = true;
    SOPC_PubSubConfiguration* config = SOPC_PubSubConfiguration_Create();
    
    SOPC_PubSubConnection* connection = NULL;

    /* 1 publisher connection */
    alloc = SOPC_PubSubConfiguration_Allocate_PubConnection_Array(config, 1);
    
    /** Publisher connection 0 **/
    
    if (alloc)
    {
        // Set address
        connection = SOPC_PubSubConfiguration_Get_PubConnection_At(config, 0);
        SOPC_ASSERT(NULL != connection);
        alloc = SOPC_PubSubConnection_Set_Address(connection, "opc.udp://232.1.2.100:4840");
    }
    
        if (alloc)
        {
            // Set publisher id
            SOPC_PubSubConnection_Set_PublisherId_UInteger(connection, 42);
        }
    
  if (alloc)
    {

        const char* itf_name = "";
        if (itf_name[0] == '\0')
        {
            // Force default interface if not specifi/ed
            itf_name = SOPC_Platform_Get_Default_Net_Itf();
        }
        if (itf_name[0] != '\0')
        {
            alloc = SOPC_PubSubConnection_Set_InterfaceName(connection, itf_name);
        }
    }
    // Set acyclic publisher mode
    // SOPC_PubSubConnection_Set_AcyclicPublisher(connection, 0);
    
    if (alloc)
    {
        // Allocate 2 writer groups (messages)
        alloc = SOPC_PubSubConnection_Allocate_WriterGroup_Array(connection, 2);
    }

    /* 2 Published Datasets */
    alloc = SOPC_PubSubConfiguration_Allocate_PublishedDataSet_Array(config, 2);
    
    SOPC_DataSetWriter* writer = NULL;
    /*** Pub Message 14 ***/
    
    if (alloc)
    {
        // GroupId = 14
        // GroupVersion = 1
        // Interval = 100.000000 ms
        // Offest = -1 us
        // mqttTopic = NULL
        // encoding = SOPC_MessageEncodeUADP
        writer = SOPC_PubSubConfig_SetPubMessageAt(connection, 0, 14, 1, 100.000000, SOPC_SecurityMode_None);
        alloc = NULL != writer;
    }
    
    // if (alloc)
    // {
    //    // 1 data sets for message 14
    //    alloc = SOPC_WriterGroup_Allocate_DataSetWriter_Array(writer, 1);
    // }

    
  
    /*** DataSetMessage No 1 of message 14 ***/
    
    // SOPC_DataSetWriter* writer = NULL;
    SOPC_PublishedDataSet* dataset = NULL;
    if (alloc)
    {
        // writer = SOPC_WriterGroup_Get_DataSetWriter_At(writerGroup, 0);
        // SOPC_ASSERT(NULL != writer);
        // WriterId = 0

        dataset = SOPC_PubSubConfig_InitDataSet(config, 0, writer, 2);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=1;s=PubBool", SOPC_Boolean_Id); // varBool
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 1, "ns=1;s=PubString", SOPC_String_Id); // varString
    }
    
    // if (alloc)
    // {
    //     alloc = SOPC_WriterGroup_Allocate_SecurityKeyServices_Array(writer, 1);
    // }
    
    // if (alloc)
    // {
    // 
    //     SOPC_SecurityKeyServices* sks = SOPC_WriterGroup_Get_SecurityKeyServices_At(writerGroup, 0);
    //     SOPC_SerializedCertificate* cert = NULL;
    //     alloc = SOPC_SecurityKeyServices_Set_EndpointUrl(sks, "opc.tcp://localhost:4841");
    //     SOPC_ReturnStatus status = SOPC_KeyManager_SerializedCertificate_CreateFromFile("./server_public/sks_server_2k_cert.der", &cert);
    //     if(SOPC_STATUS_OK == status) {
    //         SOPC_SecurityKeyServices_Set_ServerCertificate(sks, cert);
    //     }
    //     alloc = (alloc && SOPC_STATUS_OK == status);
    // }
    /*** Pub Message 15 ***/
    
    if (alloc)
    {
        // GroupId = 15
        // GroupVersion = 1
        // Interval = 1000.000000 ms
        // Offest = -1 us
        // mqttTopic = NULL
        // encoding = SOPC_MessageEncodeUADP
        writer = SOPC_PubSubConfig_SetPubMessageAt(connection, 1, 15, 1, 1000.000000, SOPC_SecurityMode_None);
        alloc = NULL != writer;
    }
    
    // if (alloc)
    // {
    //    // 1 data sets for message 15
    //    alloc = SOPC_WriterGroup_Allocate_DataSetWriter_Array(writer, 1);
    // }

    
    /*** DataSetMessage No 1 of message 15 ***/
    
    if (alloc)
    {
        // writer = SOPC_WriterGroup_Get_DataSetWriter_At(writerGroup, 0);
        // SOPC_ASSERT(NULL != writer);
        // WriterId = 0
        dataset = SOPC_PubSubConfig_InitDataSet(config, 1, writer, 3);
        alloc = NULL != dataset;
    }
    if (alloc)
    {
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 0, "ns=1;s=PubInt", SOPC_Int64_Id); // varInt
        SOPC_PubSubConfig_SetPubVariableAt(dataset, 1, "ns=1;s=PubUInt", SOPC_UInt64_Id); // varUInt
        uint32_t arrayDimensions_2 = 3;
        SOPC_PubSubConfig_SetPubVariableAt_arr(dataset, 2, "ns=1;s=PubArrayInt", SOPC_Int64_Id, 1, &arrayDimensions_2); // varInt
    }
    

    // /* 1 connection Sub */
    // alloc = SOPC_PubSubConfiguration_Allocate_SubConnection_Array(config, 1);
    // 
    // /** Subscriber connection 0 **/
    // 
    // if (alloc)
    // {
    //     // Set subscriber id and address
    //     connection = SOPC_PubSubConfiguration_Get_SubConnection_At(config, 0);
    //     alloc = SOPC_PubSubConnection_Set_Address(connection, "opc.udp://232.1.2.100:4840");
    // }
    //
    // if (alloc)
    // {
    //     // 2 sub messages
    //     alloc = SOPC_PubSubConnection_Allocate_ReaderGroup_Array(connection, 2);
    // }
    //
    //     
    // SOPC_DataSetReader* dsReader = NULL;
    // SOPC_ReaderGroup* readerGroup = NULL;
    // /*** Sub Message 14 ***/
    // 
    // if (alloc)
    // {
    //     // Allocate 1 datasets
    //     // GroupId = 14
    //     // GroupVersion = 1
    //     // PubId = 42
    //     // mqttTopic = NULL
    //     SOPC_Conf_PublisherId pubId = {.type = SOPC_UInteger_PublisherId, .data.uint = 42};
    //     readerGroup = SOPC_PubSubConfig_SetSubMessageAt(connection, 0, SOPC_SecurityMode_SignAndEncrypt, 14, 1, pubId, 1, NULL);
    //     alloc = NULL != readerGroup;
    // }
    // 
    // /*** DataSetMessage No 1 of message 14 ***/
    // 
    // if (alloc)
    // {
    //     // Interval = 100.000000 ms
    //     dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 0, 0, 100.000000);
    //     alloc = NULL != dsReader;
    // }
    // 
    // if (alloc)
    // {
    //     alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 2);
    // }
    //
    // if (alloc)
    // {
    // 
    //         SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;s=SubBool", SOPC_Boolean_Id, -1, NULL); // varBool
    //         SOPC_PubSubConfig_SetSubVariableAt(dsReader, 1, "ns=1;s=SubString", SOPC_String_Id, -1, NULL); // varString
    // }
    // 
    // if (alloc)
    // {
    //     alloc = SOPC_ReaderGroup_Allocate_SecurityKeyServices_Array(readerGroup, 1);
    // }
    // 
    // if (alloc)
    // {
    // 
    //     SOPC_SecurityKeyServices* sks = SOPC_ReaderGroup_Get_SecurityKeyServices_At(readerGroup, 0);
    //     SOPC_SerializedCertificate* cert = NULL;
    //     alloc = SOPC_SecurityKeyServices_Set_EndpointUrl(sks, "opc.tcp://localhost:4841");
    //     SOPC_ReturnStatus status = SOPC_KeyManager_SerializedCertificate_CreateFromFile("./server_public/sks_server_2k_cert.der", &cert);
    //     if(SOPC_STATUS_OK == status) {
    //         SOPC_SecurityKeyServices_Set_ServerCertificate(sks, cert);
    //     }
    //     alloc = (alloc && SOPC_STATUS_OK == status);
    // }
    // /*** Sub Message 15 ***/
    // 
    // if (alloc)
    // {
    //     // Allocate 1 datasets
  
    //     // GroupVersion = 1
    //     // PubId = 42
    //     // mqttTopic = NULL
    //     SOPC_Conf_PublisherId pubId = {.type = SOPC_UInteger_PublisherId, .data.uint = 42};
    //     readerGroup = SOPC_PubSubConfig_SetSubMessageAt(connection, 1, SOPC_SecurityMode_None, 15, 1, pubId, 1, NULL);
    //     alloc = NULL != readerGroup;
    // }
    // 
    // /*** DataSetMessage No 1 of message 15 ***/
    // 
    // if (alloc)
    // {
    //     // Interval = 1000.000000 ms
    //     dsReader = SOPC_PubSubConfig_SetReaderAt(readerGroup, 0, 0, 1000.000000);
    //     alloc = NULL != dsReader;
    // }
    // 
    // if (alloc)
    // {
    //     alloc = SOPC_PubSubConfig_SetSubNbVariables(dsReader, 3);
    // }
    //
    // if (alloc)
    // {
    // 
    //         SOPC_PubSubConfig_SetSubVariableAt(dsReader, 0, "ns=1;s=SubInt", SOPC_Int64_Id, -1, NULL); // varInt
    //         SOPC_PubSubConfig_SetSubVariableAt(dsReader, 1, "ns=1;s=SubUInt", SOPC_UInt64_Id, -1, NULL); // varUInt
    //     uint32_t arrayDimensions_2[1] = {0};
    //         SOPC_PubSubConfig_SetSubVariableAt(dsReader, 2, "ns=1;s=SubArrayInt", SOPC_Int64_Id, 1, arrayDimensions_2); // varInt
    // }
    

    if (!alloc)
    {
        SOPC_PubSubConfiguration_Delete(config);
        return NULL;
    }

    return config;
}
    
